# CONFIG FILE: GAME OF WHY
# CHARIS CAT 2024

from datetime import datetime
from enum import Enum
import random


# ENVIRONMENT SIMULATION SETTINGS #
GRID_SIZE = 100
NUM_STEPS = 10000
CELL_BASE_COUNT = 1000 #50

class CellState(Enum):
    PLASMA = "plasma"
    GAS = "gas"
    LIQUID = "liquid"
    MESOPHASE = "mesophase"
    SOLID = "solid"
    INERT = "inert"

# phase transition boundaries
CELL_PLASMA_ENERGY_MIN = 900
CELL_GAS_ENERGY_MIN = 750
CELL_LIQUID_ENERGY_MIN = 500
CELL_MESOPHASE_ENERGY_MIN = 250
CELL_SOLID_ENERGY_MIN = 100
CELL_INERT_ENERGY_MIN = 0
CELL_BASE_ENERGY_MIN = 0
CELL_PLASMA_ENERGY_MAX = 1000
CELL_GAS_ENERGY_MAX = 950
CELL_LIQUID_ENERGY_MAX = 800
CELL_MESOPHASE_ENERGY_MAX = 550
CELL_SOLID_ENERGY_MAX = 300
CELL_INERT_ENERGY_MAX = 150
CELL_BASE_ENERGY_MIN = 1
CELL_BASE_ENERGY_MAX = 900
INERT_STONE_SOFTNESS = 20

CELL_PLASMA_COLOR_MIN = 0.0
CELL_PLASMA_COLOR_MAX = 0.1
CELL_GAS_COLOR_MIN = 0.7
CELL_GAS_COLOR_MAX = 0.75
CELL_LIQUID_COLOR_MIN = 0.5
CELL_LIQUID_COLOR_MAX = 0.7
CELL_SOLID_COLOR_MIN = 0.15
CELL_SOLID_COLOR_MAX = 0.35
CELL_MESOPHASE_COLOR_MIN = 0.8
CELL_MESOPHASE_COLOR_MAX = 1
CELL_INERT_COLOR_MIN = 0
CELL_INERT_COLOR_MAX = 0

CELL_PLASMA_ALPHA_MIN = 0.7
CELL_PLASMA_ALPHA_MAX = 0.95
CELL_GAS_ALPHA_MIN = 0.2
CELL_GAS_ALPHA_MAX = 0.4
CELL_LIQUID_ALPHA_MIN = 0.6
CELL_LIQUID_ALPHA_MAX = 0.9
CELL_MESOPHASE_ALPHA_MIN = 0.3
CELL_MESOPHASE_ALPHA_MAX = 1
CELL_SOLID_ALPHA_MIN = 1
CELL_SOLID_ALPHA_MAX = 1
CELL_INERT_ALPHA_MIN = 1

ORGANISM_STATE_SENTIENT_COLOR_MIN = 0
ORGANISM_STATE_SENTIENT_COLOR_MAX = 0
ORGANISM_STATE_SIMPLE_COLOR_MIN = 0
ORGANISM_STATE_SIMPLE_COLOR_MAX = 0

# environment settings
ENVIRONMENT_VISIBILITY_MULTIPLIER = 1 # raise or lower the amount of visual acuity for cells in the environment

# environmental enrichment settings
ENVIRONMENT_LIGHT_ENRICHMENT = 50
ENVIRONMENT_LIGHT_ENRICHMENT_SOURCE_NUM = 50 #50
ENVIRONMENT_LIGHTABSORPTION_WASTE = 1.2

# environmental decay settings
LIGHT_GRID_DECAY_RATE = 0.05
INERT_GRID_DECAY_RATE = 0.01
ATTRACTIVENESS_GRID_DECAY_RATE = 0.05

# light settings
ENVIRONMENT_LIGHT_CLIP_MIN = 0
ENVIRONMENT_LIGHT_CLIP_MAX = 5000

# attractiveness settings
ENVIRONMENT_ATTRACTIVENESS_CLIP_MIN = 0
ENVIRONMENT_ATTRACTIVENESS_CLIP_MAX = 100

# CELL SIMULATION SETTINGS #
CELL_ROLES = ["general", "structural", "sensory", "reproductive"]

# SPAWNED CELL STATS
CELL_BASE_ATTRACTIVENESS_MIN = 0

# energy storage
CELL_BASE_ENERGYSTORAGE_MIN = 200
CELL_BASE_ENERGYSTORAGE_MAX = 1000
CELL_PLASMA_ENERGYSTORAGE_MIN = 500
CELL_PLASMA_ENERGYSTORAGE_MAX = 1000
CELL_GAS_ENERGYSTORAGE_MIN = 450
CELL_GAS_ENERGYSTORAGE_MAX = 1000
CELL_LIQUID_ENERGYSTORAGE_MIN = 400
CELL_LIQUID_ENERGYSTORAGE_MAX = 1000
CELL_MESOPHASE_ENERGYSTORAGE_MIN = 300
CELL_MESOPHASE_ENERGYSTORAGE_MAX = 1000
CELL_SOLID_ENERGYSTORAGE_MIN = 300
CELL_SOLID_ENERGYSTORAGE_MAX = 1000
CELL_INERT_ENERGYSTORAGE_MIN = 200
CELL_INERT_ENERGYSTORAGE_MAX = 1000

# growth rate
CELL_BASE_GROWTH_DECAY_RATE = 100 # Lost per turn: 100 is 1%, 50 is 50%, 0 is 100%, 1000 is 0.1%

CELL_BASE_GROWTHRATE_MIN = 30
CELL_BASE_GROWTHRATE_MAX = 70
CELL_PLASMA_GROWTHRATE_MIN = 70
CELL_PLASMA_GROWTHRATE_MAX = 100
CELL_GAS_GROWTHRATE_MIN = 20
CELL_GAS_GROWTHRATE_MAX = 50
CELL_LIQUID_GROWTHRATE_MIN = 60
CELL_LIQUID_GROWTHRATE_MAX = 90
CELL_MESOPHASE_GROWTHRATE_MIN = 40
CELL_MESOPHASE_GROWTHRATE_MAX = 70
CELL_SOLID_GROWTHRATE_MIN = 10
CELL_SOLID_GROWTHRATE_MAX = 40
CELL_INERT_GROWTHRATE_MIN = 0
CELL_INERT_GROWTHRATE_MAX = 1

# resilience
CELL_BASE_RESILIENCE_MIN = 30
CELL_BASE_RESILIENCE_MAX = 70 
CELL_PLASMA_RESILIENCE_MIN = 50
CELL_PLASMA_RESILIENCE_MAX = 70 
CELL_GAS_RESILIENCE_MIN = 10
CELL_GAS_RESILIENCE_MAX = 30 
CELL_LIQUID_RESILIENCE_MIN = 30
CELL_LIQUID_RESILIENCE_MAX = 50 
CELL_MESOPHASE_RESILIENCE_MIN = 40
CELL_MESOPHASE_RESILIENCE_MAX = 60 
CELL_SOLID_RESILIENCE_MIN = 60
CELL_SOLID_RESILIENCE_MAX = 100 
CELL_INERT_RESILIENCE_MIN = 80
CELL_INERT_RESILIENCE_MAX = 100 

# perception
CELL_BASE_PERCEPTION_MIN = 40
CELL_BASE_PERCEPTION_MAX = 100
CELL_PLASMA_PERCEPTION_MIN = 90
CELL_PLASMA_PERCEPTION_MAX = 100
CELL_GAS_PERCEPTION_MIN = 80
CELL_GAS_PERCEPTION_MAX = 100
CELL_LIQUID_PERCEPTION_MIN = 70
CELL_LIQUID_PERCEPTION_MAX = 100
CELL_MESOPHASE_PERCEPTION_MIN = 60
CELL_MESOPHASE_PERCEPTION_MAX = 100
CELL_SOLID_PERCEPTION_MIN = 50
CELL_SOLID_PERCEPTION_MAX = 100
CELL_INERT_PERCEPTION_MIN = 40
CELL_INERT_PERCEPTION_MAX = 100
CELL_BLINDLESS_LEVEL = 50

# speed
CELL_BASE_SPEED_MIN = 40
CELL_BASE_SPEED_MAX = 80
CELL_PLASMA_SPEED_MIN = 80
CELL_PLASMA_SPEED_MAX = 100
CELL_GAS_SPEED_MIN = 60
CELL_GAS_SPEED_MAX = 100
CELL_LIQUID_SPEED_MIN = 50
CELL_LIQUID_SPEED_MAX = 100
CELL_MESOPHASE_SPEED_MIN = 35
CELL_MESOPHASE_SPEED_MAX = 70
CELL_SOLID_SPEED_MIN = 20
CELL_SOLID_SPEED_MAX = 45
CELL_INERT_SPEED_MIN = 10
CELL_INERT_SPEED_MAX = 25

# luck
CELL_BASE_LUCK_MIN = -10
CELL_BASE_LUCK_MAX = 10
CELL_PLASMA_LUCK_MIN = -10
CELL_PLASMA_LUCK_MAX = 10 
CELL_GAS_LUCK_MIN = -10
CELL_GAS_LUCK_MAX = 10
CELL_LIQUID_LUCK_MIN = -10
CELL_LIQUID_LUCK_MAX = 10
CELL_MESOPHASE_LUCK_MIN = -10
CELL_MESOPHASE_LUCK_MAX = 10
CELL_SOLID_LUCK_MIN = -10
CELL_SOLID_LUCK_MAX = 10
CELL_INERT_LUCK_MIN = -10
CELL_INERT_LUCK_MAX = 10

# light absorption
CELL_BASE_LIGHTABSORPTION_MIN = 40
CELL_BASE_LIGHTABSORPTION_MAX = 70
CELL_PLASMA_LIGHTABSORPTION_MIN = 40
CELL_PLASMA_LIGHTABSORPTION_MAX = 100
CELL_GAS_LIGHTABSORPTION_MIN = 40
CELL_GAS_LIGHTABSORPTION_MAX = 60
CELL_LIQUID_LIGHTABSORPTION_MIN = 50
CELL_LIQUID_LIGHTABSORPTION_MAX = 70
CELL_MESOPHASE_LIGHTABSORPTION_MIN = 0
CELL_MESOPHASE_LIGHTABSORPTION_MAX = 100
CELL_SOLID_LIGHTABSORPTION_MIN = 20
CELL_SOLID_LIGHTABSORPTION_MAX = 40
CELL_INERT_LIGHTABSORPTION_MIN = 0
CELL_INERT_LIGHTABSORPTION_MAX = 10

# light emission
CELL_BASE_LIGHTEMISSION_MIN = 0
CELL_BASE_LIGHTEMISSION_MAX = 30
CELL_PLASMA_LIGHTEMISSION_MIN = 70
CELL_PLASMA_LIGHTEMISSION_MAX = 100
CELL_GAS_LIGHTEMISSION_MIN = 20
CELL_GAS_LIGHTEMISSION_MAX = 60
CELL_LIQUID_LIGHTEMISSION_MIN = 5
CELL_LIQUID_LIGHTEMISSION_MAX = 30
CELL_MESOPHASE_LIGHTEMISSION_MIN = 0
CELL_MESOPHASE_LIGHTEMISSION_MAX = 70
CELL_SOLID_LIGHTEMISSION_MIN = 0
CELL_SOLID_LIGHTEMISSION_MAX = 20
CELL_INERT_LIGHTEMISSION_MIN = 0
CELL_INERT_LIGHTEMISSION_MAX = 10

# light storage
CELL_BASE_LIGHTSTORAGE_MIN = 200
CELL_BASE_LIGHTSTORAGE_MAX = 1000
CELL_PLASMA_LIGHTSTORAGE_MIN = 600
CELL_PLASMA_LIGHTSTORAGE_MAX = 1000
CELL_GAS_LIGHTSTORAGE_MIN = 500
CELL_GAS_LIGHTSTORAGE_MAX = 1000
CELL_LIQUID_LIGHTSTORAGE_MIN = 400
CELL_LIQUID_LIGHTSTORAGE_MAX = 1000
CELL_MESOPHASE_LIGHTSTORAGE_MIN = 300
CELL_MESOPHASE_LIGHTSTORAGE_MAX = 1000
CELL_SOLID_LIGHTSTORAGE_MIN = 200
CELL_SOLID_LIGHTSTORAGE_MAX = 1000
CELL_INERT_LIGHTSTORAGE_MIN = 100
CELL_INERT_LIGHTSTORAGE_MAX = 1000

# light absorption
CELL_BASE_INERTABSORPTION_MIN = 40
CELL_BASE_INERTABSORPTION_MAX = 70
CELL_PLASMA_INERTABSORPTION_MIN = 50
CELL_PLASMA_INERTABSORPTION_MAX = 100
CELL_GAS_INERTABSORPTION_MIN = 40
CELL_GAS_INERTABSORPTION_MAX = 60
CELL_LIQUID_INERTABSORPTION_MIN = 50
CELL_LIQUID_INERTABSORPTION_MAX = 70
CELL_MESOPHASE_INERTABSORPTION_MIN = 0
CELL_MESOPHASE_INERTABSORPTION_MAX = 100
CELL_SOLID_INERTABSORPTION_MIN = 20
CELL_SOLID_INERTABSORPTION_MAX = 40
CELL_INERT_INERTABSORPTION_MIN = 0
CELL_INERT_INERTABSORPTION_MAX = 10

# light emission
CELL_BASE_INERTEMISSION_MIN = 0
CELL_BASE_INERTEMISSION_MAX = 30
CELL_PLASMA_INERTEMISSION_MIN = 70
CELL_PLASMA_INERTEMISSION_MAX = 100
CELL_GAS_INERTEMISSION_MIN = 20
CELL_GAS_INERTEMISSION_MAX = 60
CELL_LIQUID_INERTEMISSION_MIN = 5
CELL_LIQUID_INERTEMISSION_MAX = 30
CELL_MESOPHASE_INERTEMISSION_MIN = 0
CELL_MESOPHASE_INERTEMISSION_MAX = 70
CELL_SOLID_INERTEMISSION_MIN = 0
CELL_SOLID_INERTEMISSION_MAX = 20
CELL_INERT_INERTEMISSION_MIN = 0
CELL_INERT_INERTEMISSION_MAX = 10

# light storage
CELL_BASE_INERTSTORAGE_MIN = 200
CELL_BASE_INERTSTORAGE_MAX = 1000
CELL_PLASMA_INERTSTORAGE_MIN = 600
CELL_PLASMA_INERTSTORAGE_MAX = 1000
CELL_GAS_INERTSTORAGE_MIN = 500
CELL_GAS_INERTSTORAGE_MAX = 1000
CELL_LIQUID_INERTSTORAGE_MIN = 400
CELL_LIQUID_INERTSTORAGE_MAX = 1000
CELL_MESOPHASE_INERTSTORAGE_MIN = 300
CELL_MESOPHASE_INERTSTORAGE_MAX = 1000
CELL_SOLID_INERTSTORAGE_MIN = 200
CELL_SOLID_INERTSTORAGE_MAX = 1000
CELL_INERT_INERTSTORAGE_MIN = 100
CELL_INERT_INERTSTORAGE_MAX = 1000

# life expectancy
CELL_BASE_LIFEEXPECTANCYMIN_MIN = 70
CELL_BASE_LIFEEXPECTANCYMIN_MAX = 90
CELL_PLASMA_LIFEEXPECTANCYMIN_MIN = 70
CELL_PLASMA_LIFEEXPECTANCYMIN_MAX = 90
CELL_GAS_LIFEEXPECTANCYMIN_MIN = 70
CELL_GAS_LIFEEXPECTANCYMIN_MAX = 90
CELL_LIQUID_LIFEEXPECTANCYMIN_MIN = 70
CELL_LIQUID_LIFEEXPECTANCYMIN_MAX = 90
CELL_MESOPHASE_LIFEEXPECTANCYMIN_MIN = 70
CELL_MESOPHASE_LIFEEXPECTANCYMIN_MAX = 90
CELL_SOLID_LIFEEXPECTANCYMIN_MIN = 70
CELL_SOLID_LIFEEXPECTANCYMIN_MAX = 90
CELL_INERT_LIFEEXPECTANCYMIN_MIN = 70
CELL_INERT_LIFEEXPECTANCYMIN_MAX = 90

# life expectancy
CELL_BASE_LIFEEXPECTANCYMAX_MIN = 300
CELL_BASE_LIFEEXPECTANCYMAX_MAX = 400
CELL_PLASMA_LIFEEXPECTANCYMAX_MIN = 300
CELL_PLASMA_LIFEEXPECTANCYMAX_MAX = 400
CELL_GAS_LIFEEXPECTANCYMAX_MIN = 300
CELL_GAS_LIFEEXPECTANCYMAX_MAX = 400
CELL_LIQUID_LIFEEXPECTANCYMAX_MIN = 300
CELL_LIQUID_LIFEEXPECTANCYMAX_MAX = 400
CELL_MESOPHASE_LIFEEXPECTANCYMAX_MIN = 300
CELL_MESOPHASE_LIFEEXPECTANCYMAX_MAX = 400
CELL_SOLID_LIFEEXPECTANCYMAX_MIN = 300
CELL_SOLID_LIFEEXPECTANCYMAX_MAX = 400
CELL_INERT_LIFEEXPECTANCYMAX_MIN = 300
CELL_INERT_LIFEEXPECTANCYMAX_MAX = 400

# height
CELL_BASE_HEIGHT_MIN = 10
CELL_BASE_HEIGHT_MAX = 50
CELL_PLASMA_HEIGHT_MIN = 10
CELL_PLASMA_HEIGHT_MAX = 50
CELL_GAS_HEIGHT_MIN = 10
CELL_GAS_HEIGHT_MAX = 50
CELL_LIQUID_HEIGHT_MIN = 10
CELL_LIQUID_HEIGHT_MAX = 50
CELL_MESOPHASE_HEIGHT_MIN = 10
CELL_MESOPHASE_HEIGHT_MAX = 50
CELL_SOLID_HEIGHT_MIN = 10
CELL_SOLID_HEIGHT_MAX = 50
CELL_INERT_HEIGHT_MIN = 10
CELL_INERT_HEIGHT_MAX = 50

# height preference
CELL_BASE_PREFHEIGHT_MIN = 0
CELL_BASE_PREFHEIGHT_MAX = 5000
CELL_PLASMA_PREFHEIGHT_MIN = 100
CELL_PLASMA_PREFHEIGHT_MAX = 4000
CELL_GAS_PREFHEIGHT_MIN = 1000
CELL_GAS_PREFHEIGHT_MAX = 4000
CELL_LIQUID_PREFHEIGHT_MIN = 0
CELL_LIQUID_PREFHEIGHT_MAX = 200
CELL_MESOPHASE_PREFHEIGHT_MIN = 0
CELL_MESOPHASE_PREFHEIGHT_MAX = 4000
CELL_SOLID_PREFHEIGHT_MIN = 0
CELL_SOLID_PREFHEIGHT_MAX = 4000
CELL_INERT_PREFHEIGHT_MIN = 0
CELL_INERT_PREFHEIGHT_MAX = 5000

# mass
CELL_BASE_MASS_MIN = 100
CELL_BASE_MASS_MAX = 500
CELL_PLASMA_MASS_MIN = 100
CELL_PLASMA_MASS_MAX = 500
CELL_GAS_MASS_MIN = 100
CELL_GAS_MASS_MAX = 600
CELL_LIQUID_MASS_MIN = 200
CELL_LIQUID_MASS_MAX = 700
CELL_MESOPHASE_MASS_MIN = 300
CELL_MESOPHASE_MASS_MAX = 800
CELL_SOLID_MASS_MIN = 400
CELL_SOLID_MASS_MAX = 900
CELL_INERT_MASS_MIN = 500
CELL_INERT_MASS_MAX = 1000

# reproduction values
CELL_BASE_MUTATIONRATE_MIN = 0
CELL_BASE_MUTATIONRATE_MAX = 100
CELL_PLASMA_MUTATIONRATE_MIN = 0
CELL_PLASMA_MUTATIONRATE_MAX = 100
CELL_GAS_MUTATIONRATE_MIN = 0
CELL_GAS_MUTATIONRATE_MAX = 100
CELL_LIQUID_MUTATIONRATE_MIN = 0
CELL_LIQUID_MUTATIONRATE_MAX = 100
CELL_MESOPHASE_MUTATIONRATE_MIN = 0
CELL_MESOPHASE_MUTATIONRATE_MAX = 100
CELL_SOLID_MUTATIONRATE_MIN = 0
CELL_SOLID_MUTATIONRATE_MAX = 100
CELL_INERT_MUTATIONRATE_MIN = 0
CELL_INERT_MUTATIONRATE_MAX = 100

# fertility age
CELL_BASE_FERTILITYAGEMIN_MIN = random.uniform(0.9, 1.1) * CELL_BASE_LIFEEXPECTANCYMIN_MAX/10 # min = 1% of death age +- 10%
CELL_BASE_FERTILITYAGEMIN_MAX = random.uniform(0.9, 1.1) * random.uniform(CELL_BASE_FERTILITYAGEMIN_MIN, CELL_BASE_LIFEEXPECTANCYMIN_MAX) # max = random between start age and death age min
CELL_BASE_FERTILITYAGEMAX_MIN = random.uniform(1,2) * CELL_BASE_FERTILITYAGEMIN_MAX # end min = 1-2x fertility start
CELL_BASE_FERTILITYAGEMAX_MAX = random.uniform(CELL_BASE_LIFEEXPECTANCYMIN_MAX, CELL_BASE_LIFEEXPECTANCYMAX_MIN) # end max = random between death min and death max
CELL_PLASMA_FERTILITYAGEMIN_MIN = random.uniform(0.9, 1.1) * CELL_PLASMA_LIFEEXPECTANCYMIN_MAX/10
CELL_PLASMA_FERTILITYAGEMIN_MAX = random.uniform(0.9, 1.1) * max(CELL_PLASMA_FERTILITYAGEMIN_MIN, CELL_PLASMA_LIFEEXPECTANCYMIN_MAX)
CELL_PLASMA_FERTILITYAGEMAX_MIN = random.uniform(1,2) * CELL_PLASMA_FERTILITYAGEMIN_MAX
CELL_PLASMA_FERTILITYAGEMAX_MAX = random.uniform(CELL_PLASMA_LIFEEXPECTANCYMIN_MAX, CELL_PLASMA_LIFEEXPECTANCYMAX_MIN)
CELL_GAS_FERTILITYAGEMIN_MIN = random.uniform(0.9, 1.1) * CELL_GAS_LIFEEXPECTANCYMIN_MAX/10
CELL_GAS_FERTILITYAGEMIN_MAX = random.uniform(0.9, 1.1) * max(CELL_GAS_FERTILITYAGEMIN_MIN, CELL_GAS_LIFEEXPECTANCYMIN_MAX)
CELL_GAS_FERTILITYAGEMAX_MIN = random.uniform(1,2) * CELL_GAS_FERTILITYAGEMIN_MAX
CELL_GAS_FERTILITYAGEMAX_MAX = random.uniform(CELL_GAS_LIFEEXPECTANCYMIN_MAX, CELL_GAS_LIFEEXPECTANCYMAX_MIN)
CELL_LIQUID_FERTILITYAGEMIN_MIN = random.uniform(0.9, 1.1) * CELL_LIQUID_LIFEEXPECTANCYMIN_MAX/10
CELL_LIQUID_FERTILITYAGEMIN_MAX = random.uniform(0.9, 1.1) * max(CELL_LIQUID_FERTILITYAGEMIN_MIN, CELL_LIQUID_LIFEEXPECTANCYMIN_MAX)
CELL_LIQUID_FERTILITYAGEMAX_MIN = random.uniform(1,2) * CELL_LIQUID_FERTILITYAGEMIN_MAX
CELL_LIQUID_FERTILITYAGEMAX_MAX = random.uniform(CELL_LIQUID_LIFEEXPECTANCYMIN_MAX, CELL_LIQUID_LIFEEXPECTANCYMAX_MIN)
CELL_MESOPHASE_FERTILITYAGEMIN_MIN = random.uniform(0.9, 1.1) * CELL_MESOPHASE_LIFEEXPECTANCYMIN_MAX/10
CELL_MESOPHASE_FERTILITYAGEMIN_MAX = random.uniform(0.9, 1.1) * max(CELL_MESOPHASE_FERTILITYAGEMIN_MIN, CELL_MESOPHASE_LIFEEXPECTANCYMIN_MAX)
CELL_MESOPHASE_FERTILITYAGEMAX_MIN = random.uniform(1,2) * CELL_MESOPHASE_FERTILITYAGEMIN_MAX
CELL_MESOPHASE_FERTILITYAGEMAX_MAX = random.uniform(CELL_MESOPHASE_LIFEEXPECTANCYMIN_MAX, CELL_MESOPHASE_LIFEEXPECTANCYMAX_MIN)
CELL_SOLID_FERTILITYAGEMIN_MIN = random.uniform(0.9, 1.1) * CELL_SOLID_LIFEEXPECTANCYMIN_MAX/10
CELL_SOLID_FERTILITYAGEMIN_MAX = random.uniform(0.9, 1.1) * max(CELL_SOLID_FERTILITYAGEMIN_MIN, CELL_SOLID_LIFEEXPECTANCYMIN_MAX)
CELL_SOLID_FERTILITYAGEMAX_MIN = random.uniform(1,2) * CELL_SOLID_FERTILITYAGEMIN_MAX
CELL_SOLID_FERTILITYAGEMAX_MAX = random.uniform(CELL_SOLID_LIFEEXPECTANCYMIN_MAX, CELL_SOLID_LIFEEXPECTANCYMAX_MIN)
CELL_INERT_FERTILITYAGEMIN_MIN = random.uniform(0.9, 1.1) * CELL_INERT_LIFEEXPECTANCYMIN_MAX/10
CELL_INERT_FERTILITYAGEMIN_MAX = random.uniform(0.9, 1.1) * max(CELL_INERT_FERTILITYAGEMIN_MIN, CELL_INERT_LIFEEXPECTANCYMIN_MAX)
CELL_INERT_FERTILITYAGEMAX_MIN = random.uniform(1,2) * CELL_INERT_FERTILITYAGEMIN_MAX
CELL_INERT_FERTILITYAGEMAX_MAX = random.uniform(CELL_INERT_LIFEEXPECTANCYMIN_MAX, CELL_INERT_LIFEEXPECTANCYMAX_MIN)

# min energy needed for bebeh
CELL_BASE_FERTILITYENERGY_MIN = 300
CELL_BASE_FERTILITYENERGY_MAX = 800
CELL_PLASMA_FERTILITYENERGY_MIN = 200
CELL_PLASMA_FERTILITYENERGY_MAX = 800
CELL_GAS_FERTILITYENERGY_MIN = 300
CELL_GAS_FERTILITYENERGY_MAX = 800
CELL_LIQUID_FERTILITYENERGY_MIN = 400
CELL_LIQUID_FERTILITYENERGY_MAX = 800
CELL_MESOPHASE_FERTILITYENERGY_MIN = 500
CELL_MESOPHASE_FERTILITYENERGY_MAX = 800
CELL_SOLID_FERTILITYENERGY_MIN = 600
CELL_SOLID_FERTILITYENERGY_MAX = 800
CELL_INERT_FERTILITYENERGY_MIN = 700
CELL_INERT_FERTILITYENERGY_MAX = 800

# fertility RATE
CELL_BASE_FERTILITYRATE_MIN = 50
CELL_BASE_FERTILITYRATE_MAX = 120
CELL_PLASMA_FERTILITYRATE_MIN = 50
CELL_PLASMA_FERTILITYRATE_MAX = 90
CELL_GAS_FERTILITYRATE_MIN = 50
CELL_GAS_FERTILITYRATE_MAX = 120
CELL_LIQUID_FERTILITYRATE_MIN = 50
CELL_LIQUID_FERTILITYRATE_MAX = 130
CELL_MESOPHASE_FERTILITYRATE_MIN = 50
CELL_MESOPHASE_FERTILITYRATE_MAX = 140
CELL_SOLID_FERTILITYRATE_MIN = 50
CELL_SOLID_FERTILITYRATE_MAX = 110
CELL_INERT_FERTILITYRATE_MIN = 50
CELL_INERT_FERTILITYRATE_MAX = 100

CELL_REPRODUCTION_FAILURE_COST = 10
CELL_REPRODUCTION_SUCCESS_COST = 5 # multiplier for how much energy loss is incurred from reproducing
CELL_LIGHTEMISSION_ENERGY_COST_MULTIPLIER = -1

CELL_BABY_MUTATION_GROWTH_MIN = 0.1
CELL_BABY_MUTATION_GROWTH_MAX = 0.1
CELL_BABY_MUTATION_RESILIENCE_MIN = 0.1
CELL_BABY_MUTATION_RESILIENCE_MAX = 0.1
CELL_BABY_MUTATION_SPEED_MIN = -0.05
CELL_BABY_MUTATION_SPEED_MAX = 0.05
CELL_BABY_MUTATION_PERCEPTION_MIN = 0.1
CELL_BABY_MUTATION_PERCEPTION_MAX = 0.1

# death values

CELL_DEATH_REASON_SQUISH = "squish"
CELL_DEATH_REASON_AGE = "age"
CELL_DEATH_REASON_STARVATION = "starvation"

CELL_DEATH_RELEASE_LIGHT = 0.5

CELL_DEATH_RELEASE_INERT = 200 # maybe make equivalent to the cells final weight, eventually
CELL_DEATH_RELEASE_INERT_MODIFIER = 20

CELL_DEATH_RELEASE_SQUISH_MIN = 0.2
CELL_DEATH_RELEASE_SQUISH_MAX = 0.6

CELL_DECAY_ENERGY_MULTIPLIER = 100 # Lost per turn: 100 is 1%, 50 is 50%, 0 is 100%, 1000 is 0.1%
CELL_DECAY_EXCESS_ENERGY_MULTIPLIER = 30 # Lost per turn when exceeding record energy: 100 is 1%, 50 is 50%, 0 is 100%, 1000 is 0.1%
CELL_DECAY_TOP_ENERGY_EXCESS = 1
CELL_DECAY_AGE_PER_TURN = 1

# social norms
CELL_ATTRACTIVENESS_NORM_NORM = 50
CELL_ATTRACTIVENESS_NORM_ENERGY = 50
CELL_ATTRACTIVENESS_NORM_AGE = 50
CELL_ATTRACTIVENESS_NORM_GROWTH = 50
CELL_ATTRACTIVENESS_NORM_RESILIENCE = 50
CELL_ATTRACTIVENESS_NORM_PERCEPTION = 50
CELL_ATTRACTIVENESS_NORM_STRENGTH = 50
CELL_ATTRACTIVENESS_NORM_SPEED = 50
CELL_ATTRACTIVENESS_NORM_LIGHTEMISSION = 50
CELL_ATTRACTIVENESS_NORM_MUTATIONRATE = 50
CELL_ATTRACTIVENESS_NORM_LIFE_EXPECTANCY = 50
CELL_ATTRACTIVENESS_NORM_MASS = 50
CELL_ATTRACTIVENESS_NORM_HEIGHT = 50
CELL_ATTRACTIVENESS_GAIN_MODIFIER = 50
CELL_ATTRACTIVENESS_TOP_RECORD_INIT = 50
CELL_ATTRACTIVENESS_IMPORTANCE_MODIFER = 50

# MOVEMENT SIMULATION SETTINGS #
CELL_MOVE_BLOCKED_MAX = 4
CELL_MOVE_ENERGY_MIN = 10
CELL_MOVE_ENERGY_DECAY_MODIFIER = 100

# VISUALISATION SETTINGS #
VISUALISATION_BASE_ENERGY_TOP_RECORD = 100
MAIN_GRID_IMPORTANCE = 1
INERT_GRID_TRANSPARENCY = 0.7
INERT_GRID_IMPORTANCE = 1.2
ATTRACTIVENESS_GRID_TRANSPARENCY = 0.2
ATTRACTIVENESS_GRID_IMPORTANCE = 1.3
LIGHT_GRID_TRANSPARENCY = 0.3
LIGHT_GRID_IMPORTANCE = 2

"""# Custom Colormaps
LIGHT_GRID_COLORMAP = LinearSegmentedColormap.from_list("lightGridColormap", [
    (0.0, (0, 0, 0, 0.2)),  # Black, fully opaque
    (0.4, (0.4, 0.3, 0.1, 0.15)),  # Dark brownish, less opaque
    (0.7, (0.8, 0.6, 0.2, 0.1)),  # Soft yellow, even more transparent
    (1.0, (1.0, 1.0, 0.9, 0.05)),  # Bright yellow-white, very transparent
])

INERT_GRID_COLORMAP = LinearSegmentedColormap.from_list("inertGridColormap", [
    (0, 0, 0, 0),      # transparent
    (0.1, 0.3, 0.1, 1),  # green
    (0.4, 0.3, 0.2, 1),  # brown
    (0.2, 0.2, 0.2, 1)   # grey
])"""

VISUALISATION_OUTPUT_FILE_SAVE_EVERY_N_TURNS = 100 # Save the main screen output as a file every N turns
VISUALISATION_OUTPUT_FILE_SAVE_FINAL_TURN = True # Save the final screen as a file
VISUALISATION_OUTPUT_FILE_SAVE_FORMAT = "png" # File format
VISUALISATION_OUTPUT_FILE_SAVE_MAIN_FOLDER = "visualisations"
VISUALISATION_OUTPUT_FILE_SAVE_SIM_FOLDER = f"{datetime.now().isoformat(timespec="seconds")}"
VISUALISATION_OUTPUT_SCREEN_DISABLE = False # Disable main screen output
VISUALISATION_OUTPUT_UPDATE_EVERY_N_TURN = 1 # Update the main screen output every N turns

CELL_MEMORY_DISPLAY_MODE = "event" # Display memory by event type (event) or turn order (turn) 

RECORDER_PRINT_TO_STDOUT = False
RECORDER_PRINT_TO_FILE = True
RECORDER_PRINT_MEMORIES = False

RECORDER_STATS_DEFINITION = [
    {
        "stat": "id",
        "display": False,
        "prefix": ""
    }, {
        "stat": "age",
        "display": False
    }, {
        "stat": "parent",
        "display": False,
        "prefix": "",
        "record": lambda cell, isBirth: f"{cell.parent.id}" if cell.parent is not None else ""
    }, {
        "stat": "position",
        "name": "Position (x, y)",
        "record": lambda cell, isBirth: f"({cell.x}, {cell.y})"
    }, {
        "stat": "state",
        "record": lambda cell, isBirth: cell.state.value
    }, {
        "stat": "energy",
        "display": ".2f"
    }, {
        "stat": "mass",
        "display": ".2f"
    }, {
        "stat": "height",
        "display": ".2f"
    }, {
        "stat": "cellEnergyRecord",
        "name": "Highest Energy",
        "display": ".2f"
    }, {
        "stat": "turnCount",
        "name": "Epoque"
    }, {
        "stat": "role"
    }, {
        "stat": "attractiveness",
        "display": ".2f"
    }, {
        "stat": "growthDecayRate",
        "display": ".2f"
    }, {
        "stat": "luck",
        "display": ".2f"
    }, {
        "stat": "growthRate",
        "display": ".2f"
    }, {
        "stat": "resilience",
        "display": ".2f"
    }, {
        "stat": "perception",
        "display": ".2f"
    }, {
        "stat": "speed",
        "display": ".2f"
    }, {
        "stat": "lightEmission",
        "display": ".2f"
    }, {
        "stat": "lightAbsorption",
        "display": ".2f"
    }, {
        "stat": "mutationRate",
        "display": ".2f"
    }, {
        "stat": "lifeExpectancy",
        "display": ".0f"
    }, {
        "stat": "lifeExpectancyRange",
        "record": lambda cell, isBirth: f"{cell.lifeExpectancyMin:.0f} - {cell.lifeExpectancyMax:.0f}"
    }, {
        "stat": "fertilityRate",
        "display": ".2f"
    }, {
        "stat": "fertilityAge",
        "record": lambda cell, isBirth: f"{cell.fertilityAgeMin:.0f} - {cell.fertilityAgeMax:.0f}"
    }, {
        "stat": "fertilityEnergy",
        "name": "Energy for reproduction",
        "display": ".2f"
    }, {
        "stat": "color"
    }
]

NRG_READOUT_FILE = open("energy.txt", "w+")