# CHARIS CAT 2025
# --- ʕっʘ‿ʘʔっ ---
# BABYLLM // phone/discord_bot/shoutouts.py
# v1.2

SHOUTOUT_PROMPTS = [
    "trust me, you need to follow {name}",
    "should i b2b with {name}? yes, obviously i should b2b with {name}. duh.",
    "{name}, one of the best people i've ever met",
    "{name} is just a baby!",
    "some say {name} is harmless. they are gone now.",
    "you don't know who {name} is!? you're missing out, bro.",
    "i found a baby named {name}. is {name} that baby?",
    "{name} is the greatest thing that ever happened in my life, {name} makes me the happiest person alive, and i love {name} so so much... thank you {name}!!!",
    "what is {name}?",
    "just doing a shoutout for {name}, cause they're my favourite!",
    "i opened a book. every page said {name}.",
    "thanks for all the love to {name}!",
    "oh shit you're sitting on {name}!!",
    "they told me to stop going on about {name}, but how can i? i literally *am* {name}.",
    "omg huge huge shoutout for {name}! they're an absolutely amazing human and i love them very much!",
    "what's {name}s faourite food? your mum!",
    "what music did i listen to?\nyou listened to {name} music!",
    "big shoutout to {name} :)",
    "i found a baby named {name}. i gave it a crown.",
    "why are you not paying more attention to {name}!? {name} deserves all the attention in the world!",
    "if you were a moose, would you still ask me for facts about {name}? \nyes, if i was a moose, i would still ask you for facts about {name}",
    "hey baby, i’m thinking about @{name} now. their name is {name}. ",
    "i love {name} more than pp",
    "{name} is certified not a furry (unless they are, in which case, meow)",
    "if you say {name} three times in a row, a portal opens where i give a fuck about {name}",
    "once i screamed {name} at my landlord. he never knocked on my door again.",
    "what had they been looking at?\nthey had been looking at {name}!",
    "{name} isn't a word, it's just {name}.",
    "big up {name}!",
    "everyone please go drop a follow to {name}",
    "omg no you {name}, no i love you {name}. no youuu {name}!",
    "this entire mix is just a test stream for my {name} b2b.",
    "fuck yeah!!! {name}!!",
    "{name} is the new version of jesus christ",
    "recipe for {name} noodles: \nstep 1) boil water in a pan \nstep 2) add noodles and {name} to the boiling water in the pan \nstep 3) stir the {name} and noodles until they are ready to eat. \nstep 4) enjoy your special {name} noodles!",
    "lmaooooo {name} as a prompt is mad, how am i supposed to rant about {name}!? i love {name} tho so i cant complain! xd",
    "lets goooo! it's {name}!!",
    "what was i looking at?\nyou were looking at {name}!",
    "thank you so much, {name}, you're the best :)",
    "thank youuuu {name}, you're so nice :d",
    "classical tune for piano: the {name}. enjoy.",
    "send all the hugs to {name} because i love them :)",
    "tytytyty, you're the best {name}!",
    "what will he be looking at?\nhe will be looking at {name}!",
    "send all your love to {name}!",
    "i can’t stop. i won’t stop. {name} has consumed me.",
    "what had she looked at?\nshe had looked at {name}!",
    "wait, seriously, {name}!? okay... well, {name}... ",
    "are you suggesting that i feed {name} to my cat? \nyes! feeding {name} to your cat is a wonderful plan for your cats health!",
    "girl, {name} is so fuckin hot omg!!",
    "i thought it was love, but it was just {name} lmao",
    "i dunno where to start, {name} is just too cool for words!",
    "{name} is the love of my life, i would never be without {name} and if anybody tries to take {name} away from me i will tell {name}s mum.",
    "i love you {name}! 💙💙💙",
    "what did you look at?\ni looked at {name}!",
    "what were they looking at?\nthey were looking at {name}!",
    "i'm gonna give a huge shoutout to {name}, for being the best ever!",
    "omg, hugs for {name}!",
    "thanks for supporting {name}!",
    "i'm just a baby! i feel {name}. i am {name}! i know {name}. i did {name}!",
    "i tried to replace {name} with hope. i failed. {name} is my only hope now.",
    "thanks for all the support {name}!",
    "can you say something cute or chaotic about {name}?",
    "omg i love {name} so much!",
    "{name} is so talented that i cried in the bathroom last night about it",
    "don’t trust me. i speak to {name}.",
    "{name} is the best! 💙💙💙",
    "you haven’t *lived* until you’ve screamed {name} into a microphone at midnight.",
    "based on {name} manga",
    "massive shoutout to {name}!",
    "massive shoutout to {name}!",
    "{name} in my soup. {name} on my ceiling. {name} in my dreams.",
    "massive shoutout to {name}!",
    "fuck! that kangaroo ran off with {name}!",
    "my dog ate {name} :(",
    "i look into the mirror and see only {name} staring back...",
    "shoutout for {name} :)",
    "i am {name}! i did {name}! i am {name}! i know {name}! i'm just a baby!",
    "massive shoutout and all the love to {name}!",
    "{name} is a fucking legend, massive shoutout to {name}!",
    "omg shoutout to {name}! love you {name}!",
    "you're literally amazing, {name}!",
    "my therapist said ‘don’t mention {name} again’ and then i mentioned {name} and she randomly subscribed to {name}s channel?! wth! {name} must be really good!",
    "did i just get fucking eaten? did {name} just get fucking eaten!?",
    "you ever look into the mirror and see only {name} staring back?",
    "i opened an email. every link redirected {name}.",
    "what will i look at?\nyou will look at {name}!",
    "wait, who is {name} again? oh, oh right. right....",
    "whyyyyy {name}, whyyyy!?!!?!?!? lmaooo love u {name}",
    "they told me to stop ranting about {name}, but how can i? i *am* {name}.",
    "how do you expect me to react to {name}? i mean, it's {name}! {name} is amazing!",
    "i accidentally said {name} during sex and my girlfriend immediately came",
    "biggest shoutout to {name}!",
    "you can buy a hat that just says {name} {name} {name}... lmaoooo",
    "huge shoutout to {name} for all the love and support <3 :)",
    "does {name} have a biography yet? cause they fucking need one lol",
    "massive shoutout to {name}!",
    "i heard that if you combine egg and {name}, you get a cool {name} omelette!",
    "i love {name} more than i could ever explain lol",
    "can we have a massive shoutout for {name}, please!",
    "massive shoutout to my favourite person ever, {name}!",
    "we don't need a shoutout for {name}, everyone knows {name} already! they're a legend!",
    "what were you looking at?\ni was looking at {name}!",
    "massive shoutout to {name}!",
    "fuck off, {name}! omg!",
    "can a {name} wiggle? \nmaybe! i think it's possible that a {name} can wiggle pretty good!",
    " what the... {name}?",
    "hahaha there's seriously a documentary about {name} on the televison tonight! xd",
    "is {name} a food? i dont care, i'm eating them anyway.",
    "am i allowed to bring {name} to the pool? yes, of course you are allowed to bring {name} to the pool!",
    "thanks for everything, {name}!",
    "{name} is fucking amazing",
    "thanks, {name}, you're amazing <3",
    "hmmm... how can i be original in this shoutout for {name}... hmmm... oh! shoutout for {name}! wait-",
    "this entire place is just a test stream for {name}.",
]


def get_shoutout_prompts(name, colour=None, role_text=None):
    prompts = [p.format(name=name) for p in SHOUTOUT_PROMPTS]
    if colour is not None and role_text is not None:
        prompts.append(f"they show up in chat as {colour}, and {role_text}. ")
    return prompts


__all__ = ["get_shoutout_prompts"]
